insert into FAMILY (FAMILYNAME, FAMILYTYPE) values ('Jackets ', 1);
insert into FAMILY (FAMILYNAME, FAMILYTYPE) values ('knitwear', 1);
insert into FAMILY (FAMILYNAME, FAMILYTYPE) values ('Jeans', 1);
insert into FAMILY (FAMILYNAME, FAMILYTYPE) values ('Dresses ', 1);
insert into FAMILY (FAMILYNAME, FAMILYTYPE) values ('Shirts', 1);
insert into FAMILY (FAMILYNAME, FAMILYTYPE) values ('pants', 1);
insert into FAMILY (FAMILYNAME, FAMILYTYPE) values ('Skirts', 1);
insert into FAMILY (FAMILYNAME, FAMILYTYPE) values ('Knitwear', 2);
insert into FAMILY (FAMILYNAME, FAMILYTYPE) values ('Jeans', 2);
insert into FAMILY (FAMILYNAME, FAMILYTYPE) values ('Jackets ', 2);
insert into FAMILY (FAMILYNAME, FAMILYTYPE) values ('Shirts', 2);
insert into FAMILY (FAMILYNAME, FAMILYTYPE) values ('Pants', 2);
insert into FAMILY (FAMILYNAME, FAMILYTYPE) values ('Knitwear', 3);
insert into FAMILY (FAMILYNAME, FAMILYTYPE) values ('Jeans', 3);
insert into FAMILY (FAMILYNAME, FAMILYTYPE) values ('Jackets ', 3);
insert into FAMILY (FAMILYNAME, FAMILYTYPE) values ('Shirts', 3);
insert into FAMILY (FAMILYNAME, FAMILYTYPE) values ('Pants', 3);
